### ISSUE TITLE
Enhancement: Change Mania Event

### ISSUE THREAD

**Issue by flowerbearttv** [Leather128/LeatherEngine#232] opened 2022-04-09 20:28 UTC
#### Please check for duplicates or similar issues before creating this issue.

There is an enhancement similar to this, but its kinda old, and no clear answer was given

## What is your suggestion, and why should it be implemented?

As the title says, an event that changes the mania/key count, value 1 is left side key count and value 2 is right side key count, if left blank that side doesn't change

**Comment by Leather128** [comment] 2022-05-29 03:22
duplicate of #79 , may be worked on one day, idk

**Closed as completed by Leather128** 2022-05-29 03:22 UTC
Labels: enhancement
